### ISSUE TITLE
Changing form col-mm-x

### ISSUE THREAD

**Issue by armankarimi** [pinax/django-forms-bootstrap#21]
Is there a way to apply a col-mm-x class to form items?
As an example, I need to render two text fields in one line. So they both should be col-md-6.
Thanks.

**Comment by marcwilson** [comment]
For horizontal forms you can do:
```
<form class="form-horizontal">
...
{{ form|as_bootstrap_horizontal:'col-xs-3' }}
...
</form>
```
which gives the label col-xs-3 and the input field col-xs-9 (or 12 minus whatever you use for the label)

But ```{{ form|as_bootstrap_inline }}``` doesn't look like it takes any parameters, so isn't as configurable it seems.

**Comment by ossanna16** [comment]
@armankarimi Does the answer above answer your question, meaning can I close this issue? 😊

**Comment by armankarimi** [comment]
Yes it perfectly did. 👍
Thanks!

**Comment by ossanna16** [comment]
Awesome, closing this now 👍
