### ISSUE TITLE
Is Django 2.0 Supported?

### ISSUE THREAD

**Issue by askpatrickw** [pinax/django-forms-bootstrap#33]
I checked the commits and the builds and I don't see anything about Django 2.0. 

Can anyone comment if they're running OK with 2.0? ty!

**Comment by KatherineMichel** [comment]
@W7PEA Hi! It appears that it is compatible with 2.0, because it's being used as part of pinax templates. pinax templates replaced pinax bootstrap in pinax. 
https://github.com/pinax/pinax-templates/blob/master/setup.py#L106

**Comment by askpatrickw** [comment]
Thank you @KatherineMichel, much appreciated!
